
package by.boot.java;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "HelloWorldSOAPImplService", targetNamespace = "http://impl.ws.server.example.webservicesidcert.com/", wsdlLocation = "file:/Users/admin/git_repositories/prosidney/WSCertification/others/service_document.wsdl")
public class HelloWorldSOAPImplService
    extends Service
{

    private final static URL HELLOWORLDSOAPIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException HELLOWORLDSOAPIMPLSERVICE_EXCEPTION;
    private final static QName HELLOWORLDSOAPIMPLSERVICE_QNAME = new QName("http://impl.ws.server.example.webservicesidcert.com/", "HelloWorldSOAPImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/Users/admin/git_repositories/prosidney/WSCertification/others/service_document.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        HELLOWORLDSOAPIMPLSERVICE_WSDL_LOCATION = url;
        HELLOWORLDSOAPIMPLSERVICE_EXCEPTION = e;
    }

    public HelloWorldSOAPImplService() {
        super(__getWsdlLocation(), HELLOWORLDSOAPIMPLSERVICE_QNAME);
    }

    public HelloWorldSOAPImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), HELLOWORLDSOAPIMPLSERVICE_QNAME, features);
    }

    public HelloWorldSOAPImplService(URL wsdlLocation) {
        super(wsdlLocation, HELLOWORLDSOAPIMPLSERVICE_QNAME);
    }

    public HelloWorldSOAPImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, HELLOWORLDSOAPIMPLSERVICE_QNAME, features);
    }

    public HelloWorldSOAPImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public HelloWorldSOAPImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns HelloWorldSOAPImplCustomized
     */
    @WebEndpoint(name = "HelloWorldSOAPImplPort")
    public HelloWorldSOAPImplCustomized getHelloWorldSOAPImplPort() {
        return super.getPort(new QName("http://impl.ws.server.example.webservicesidcert.com/", "HelloWorldSOAPImplPort"), HelloWorldSOAPImplCustomized.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns HelloWorldSOAPImplCustomized
     */
    @WebEndpoint(name = "HelloWorldSOAPImplPort")
    public HelloWorldSOAPImplCustomized getHelloWorldSOAPImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://impl.ws.server.example.webservicesidcert.com/", "HelloWorldSOAPImplPort"), HelloWorldSOAPImplCustomized.class, features);
    }

    private static URL __getWsdlLocation() {
        if (HELLOWORLDSOAPIMPLSERVICE_EXCEPTION!= null) {
            throw HELLOWORLDSOAPIMPLSERVICE_EXCEPTION;
        }
        return HELLOWORLDSOAPIMPLSERVICE_WSDL_LOCATION;
    }

}
