
package com.webservicesidcert.example.wsimport;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "HelloWorldSOAPImpl", targetNamespace = "http://ws.server.example.webservicesidcert.com/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface HelloWorldSOAPImpl {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    public String sayHelloWorldFrom(
            @WebParam(name = "arg0", partName = "arg0")
            String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    public String iExist(
            @WebParam(name = "arg0", partName = "arg0")
            String arg0);

    /**
     * 
     * @return
     *     returns Person
     */
    @WebMethod
    @WebResult(partName = "return")
    public Person getPerson();

    /**
     * 
     * @param arg0
     * @return
     *     returns byte[]
     */
    @WebMethod
    @WebResult(partName = "return")
    public byte[] getImage(
            @WebParam(name = "arg0", partName = "arg0")
            String arg0);

}
