
package com.webservicesidcert.example.wsimport;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "HelloWorldSOAPImplService", targetNamespace = "http://ws.server.example.webservicesidcert.com/", wsdlLocation = "http://localhost:9000/HelloWorld?wsdl")
public class HelloWorldSOAPImplService
    extends Service
{

    private final static URL HELLOWORLDSOAPIMPLSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(HelloWorldSOAPImplService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = HelloWorldSOAPImplService.class.getResource(".");
            url = new URL(baseUrl, "http://localhost:9000/HelloWorld?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://localhost:9000/HelloWorld?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        HELLOWORLDSOAPIMPLSERVICE_WSDL_LOCATION = url;
    }

    public HelloWorldSOAPImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public HelloWorldSOAPImplService() {
        super(HELLOWORLDSOAPIMPLSERVICE_WSDL_LOCATION, new QName("http://ws.server.example.webservicesidcert.com/", "HelloWorldSOAPImplService"));
    }

    /**
     * 
     * @return
     *     returns HelloWorldSOAPImpl
     */
    @WebEndpoint(name = "HelloWorldSOAPImplPort")
    public HelloWorldSOAPImpl getHelloWorldSOAPImplPort() {
        return super.getPort(new QName("http://ws.server.example.webservicesidcert.com/", "HelloWorldSOAPImplPort"), HelloWorldSOAPImpl.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns HelloWorldSOAPImpl
     */
    @WebEndpoint(name = "HelloWorldSOAPImplPort")
    public HelloWorldSOAPImpl getHelloWorldSOAPImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.server.example.webservicesidcert.com/", "HelloWorldSOAPImplPort"), HelloWorldSOAPImpl.class, features);
    }

}
